package com.xuejian.client.lxp.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iMUserDaoConfig;
    private final DaoConfig inviteMessageDaoConfig;

    private final IMUserDao iMUserDao;
    private final InviteMessageDao inviteMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iMUserDaoConfig = daoConfigMap.get(IMUserDao.class).clone();
        iMUserDaoConfig.initIdentityScope(type);

        inviteMessageDaoConfig = daoConfigMap.get(InviteMessageDao.class).clone();
        inviteMessageDaoConfig.initIdentityScope(type);

        iMUserDao = new IMUserDao(iMUserDaoConfig, this);
        inviteMessageDao = new InviteMessageDao(inviteMessageDaoConfig, this);

        registerDao(IMUser.class, iMUserDao);
        registerDao(InviteMessage.class, inviteMessageDao);
    }
    
    public void clear() {
        iMUserDaoConfig.getIdentityScope().clear();
        inviteMessageDaoConfig.getIdentityScope().clear();
    }

    public IMUserDao getIMUserDao() {
        return iMUserDao;
    }

    public InviteMessageDao getInviteMessageDao() {
        return inviteMessageDao;
    }

}
