package com.xuejian.client.lxp.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INVITE_MESSAGE.
 */
public class InviteMessage {

    private String nickname;
    private Long userId;
    private String avatar;
    private String gender;
    private String from;
    private String reason;
    private Long time;
    private Integer status;
    private String groupId;
    private String groupName;

    public InviteMessage() {
    }

    public InviteMessage(String from) {
        this.from = from;
    }

    public InviteMessage(String nickname, Long userId, String avatar, String gender, String from, String reason, Long time, Integer status, String groupId, String groupName) {
        this.nickname = nickname;
        this.userId = userId;
        this.avatar = avatar;
        this.gender = gender;
        this.from = from;
        this.reason = reason;
        this.time = time;
        this.status = status;
        this.groupId = groupId;
        this.groupName = groupName;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

}
