package com.aizou.peachtravel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMUSER.
 */
public class IMUser {

    private Long userId;
    private String username;
    private String nick;
    private String avatar;
    private String gender;
    private String signature;
    private String tel;
    private String memo;
    private Integer unreadMsgCount;
    private String header;
    private boolean isMyFriends;

    public IMUser() {
    }

    public IMUser(String username) {
        this.username = username;
    }

    public IMUser(Long userId, String username, String nick, String avatar, String gender, String signature, String tel, String memo, Integer unreadMsgCount, String header, boolean isMyFriends) {
        this.userId = userId;
        this.username = username;
        this.nick = nick;
        this.avatar = avatar;
        this.gender = gender;
        this.signature = signature;
        this.tel = tel;
        this.memo = memo;
        this.unreadMsgCount = unreadMsgCount;
        this.header = header;
        this.isMyFriends = isMyFriends;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Integer getUnreadMsgCount() {
        return unreadMsgCount;
    }

    public void setUnreadMsgCount(Integer unreadMsgCount) {
        this.unreadMsgCount = unreadMsgCount;
    }

    public String getHeader() {
        return header;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public boolean getIsMyFriends() {
        return isMyFriends;
    }

    public void setIsMyFriends(boolean isMyFriends) {
        this.isMyFriends = isMyFriends;
    }

}
